spring:
  application:
    name: portal-service
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8000/eureka
server:
  port: 9000
